# Generated by Django 4.1 on 2022-08-04 07:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
