# Generated by Django 4.1 on 2022-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_nature",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                    ("OTHER", "Other"),
                ],
                default="FULL_TIME",
                max_length=30,
            ),
        ),
    ]
