# Generated by Django 4.1 on 2022-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_job_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="job", name="job_category",),
        migrations.AddField(
            model_name="job",
            name="categories",
            field=models.ManyToManyField(related_name="jobs", to="jobs.jobcategory"),
        ),
    ]
