# Generated by Django 4.1 on 2022-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_jobcategory_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobcategory", options={"verbose_name_plural": "job categories"},
        ),
        migrations.AddField(
            model_name="job",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="jobcategory",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="jobcategory",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
