# Generated by Django 4.1 on 2022-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_jobcategory_options_job_logo_jobcategory_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="job", name="location",),
        migrations.AddField(
            model_name="job",
            name="locations",
            field=models.ManyToManyField(related_name="jobs", to="jobs.location"),
        ),
    ]
