# Generated by Django 4.1 on 2022-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_location_remove_job_location_job_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="number_of_jobs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_end",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_start",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="vacancy_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
