# Generated by Django 4.1 on 2022-08-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_jobcategory_number_of_jobs_alter_job_salary_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="locations",),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.location",
            ),
            preserve_default=False,
        ),
    ]
